### ISSUE TITLE
Error when dumping routes that have pagination

### ISSUE THREAD

**Issue by wagnerspirigoni-mb** [Maples7/kong-config-manager#2]
We have a lot of routes created on kong, so kong paginates it using offset, when I try to dump the conf from this kong, I receive this error

`[INFO] Ready to dump configs of kong instance main...
[ERROR] Error: RequestError: Error: Invalid URI "/routes?offset=WyI5ZTdkZDQ5MS1iYTljLTRiMWYtODk1Yy1hMDk3YTQ2NWNiZmMiXQ"
    at new RequestError (/usr/lib/node_modules/kong-config-manager/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/kong-config-manager/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/kong-config-manager/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/kong-config-manager/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.init (/usr/lib/node_modules/kong-config-manager/node_modules/request/request.js:273:17)
    at Request.RP$initInterceptor [as init] (/usr/lib/node_modules/kong-config-manager/node_modules/request-promise-core/configure/request2.js:45:29)
    at new Request (/usr/lib/node_modules/kong-config-manager/node_modules/request/request.js:127:8)
    at request (/usr/lib/node_modules/kong-config-manager/node_modules/request/index.js:53:10)
    at dumpItems (/usr/lib/node_modules/kong-config-manager/lib/dump.js:20:12)
    at rp.then.body (/usr/lib/node_modules/kong-config-manager/lib/dump.js:32:18)
From previous event:
    at getObjects.then.OBJECTS (/usr/lib/node_modules/kong-config-manager/lib/dump.js:87:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`

for what I have looked into, not sure why, but when kcm tries to follow the pagination, the URI it gets is incomplete, it only has the path, so it falls into an if on `kong-config-manager/node_modules/request/request.js` line 260 and returns the error

**Comment by Maples7** [comment]
That's wired. Can you specify the version of kong and the responses of http://localhost:8001/routes. KCM just takes the field `next` into consideration recursively without modify.

**Comment by Maples7** [comment]
By the way, you can [turn on debug mode](https://github.com/Maples7/kong-config-manager#debug) to track what happens.

**Comment by wagnerspirigoni-mb** [comment]
The version is the 0.33-enterprise, and I'm using the 0.13.x confs, as it does not support any enterprise version.

the route response is working as it should, it has the field next that points, I'm removing the routes that are in the `data` field, but this is what the response looks like

`{"next":"\/routes?offset=WyI5ZTdkZDQ5MS1iYTljLTRiMWYtODk1Yy1hMDk3YTQ2NWNiZmMiXQ","data":[],"offset":"WyI5ZTdkZDQ5MS1iYTljLTRiMWYtODk1Yy1hMDk3YTQ2NWNiZmMiXQ"}`

**Comment by Maples7** [comment]
Gotcha~ 
[As the document of Kong shows](https://docs.konghq.com/0.13.x/admin-api/#list-routes), the field `next` is supposed to be a complete URL with domain and port. Maybe the enterprise edition differs.

I'll make a patch for this issue and release a new version. Thanks for your feedback.

**Comment by wagnerspirigoni-mb** [comment]
thanks, if you need anything else, just let me know

**Comment by Maples7** [comment]
plz check [the new version 1.6.1](https://github.com/Maples7/kong-config-manager/tree/v1.6.1) to see if it works by running `npm upgrade -g kong-config-manager`

**Comment by wagnerspirigoni-mb** [comment]
Worked like a charm, thank you so much
