### ISSUE TITLE
Ignore ssl errors?

### ISSUE THREAD

**Issue by zoobab** [Maples7/kong-config-manager#5]
Hi, would it be possible to ignore SSL errors, such as this one (Error: self signed certificate), here is my config:

```
$ cat kcm-config.json
{
  "main": "https://ironic-hyena-kong-admin:8444"
}
```

And the error

```
$ DEBUG=kcm:* kcm dump
  kcm:make_program Start to make a commander instance... +0ms
  kcm:make_program Finished! +15ms
[ERROR] Error: RequestError: Error: self signed certificate
    at new RequestError (/usr/lib/node_modules/kong-config-manager/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/kong-config-manager/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/kong-config-manager/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/kong-config-manager/node_modules/request/request.js:185:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/kong-config-manager/node_modules/request/request.js:881:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:324:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1290:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by zoobab** [comment]
I tried to add this option 'insecure: true' in lib/dump.js:

```
    return rp({
      method: 'GET',
      uri: url,
      timeout: ENUMS.REQUEST_TIMEOUT,
      insecure: true
    })
```

Still the same error...

**Comment by Maples7** [comment]
Looks like a bug in `request-promise`: https://github.com/request/request-promise/issues/225

**Comment by Maples7** [comment]
> Having the same issue, insecure true didn't solve it but `rejectUnauthorized: false` did

Can you try whether it helps? I can add the option or other which is right to ignore ssl check.

**Comment by zoobab** [comment]
I can bypass it with those 3 commits:

https://github.com/azachar/kong-config-manager/commits/insecure

**Comment by zoobab** [comment]
But then I get another error:

```
$ DEBUG=* yarn kcm dump
yarn run v1.13.0
warning package.json: No license field
$ /home/centos/node_modules/.bin/kcm dump
  kcm:make_program Start to make a commander instance... +0ms
  kcm:make_program Finished! +4ms
  kcm:get-objects We obtained this version:1.1.0rc1 +82ms
[ERROR] Error: TypeError: Invalid Version: 1.1.0rc1
    at new SemVer (/home/centos/node_modules/semver/semver.js:312:11)
    at compare (/home/centos/node_modules/semver/semver.js:585:10)
    at Function.gte (/home/centos/node_modules/semver/semver.js:634:10)
    at rp.then.body (/home/centos/node_modules/kong-config-manager/tools/get_objects.js:33:19)
    at tryCatcher (/home/centos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/centos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/centos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/centos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/centos/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/centos/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/centos/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/centos/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/centos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Maples7** [comment]
Em.... as I see, `1.1.0rc1` is no compatible with [semver package](https://www.npmjs.com/package/semver).....

**Comment by zoobab** [comment]
I rolled back the version of Kong to 1.0.3 instead of 1.1.0rc1 here:

```
$ docker pull zoobab/kong:1.0.3
```

Now kcm dump works:

```
$ yarn kcm dump
yarn run v1.13.0
warning package.json: No license field
$ /home/centos/node_modules/.bin/kcm dump
[INFO] Ready to dump configs of kong instance main...
[INFO] All Finished!
Done in 1.14s.
```

**Comment by zoobab** [comment]
Other question, is there git integration, do you know how to use it?

```
$ yarn kcm apply
yarn run v1.13.0
warning package.json: No license field
$ /home/centos/node_modules/.bin/kcm apply
usage: git diff [--no-index] <path> <path>

Confirm change? [y/n]: y
[INFO] Ready to apply configs for main...

[...]

```

**Comment by Maples7** [comment]
Command `git diff --color` is used. Or you can get rid of `git` by adding option `--no-git`.

**Comment by zoobab** [comment]
For the insecure patch, should I make a PR to hardcode it by default in all cases, or should I try to build an option like curl -k?

**Comment by Maples7** [comment]
Yeah, you're welcomed to raise any PR! I think adding an options to disable ssl check might be better.

**Comment by Maples7** [comment]
#8

**Comment by Maples7** [comment]
[v1.7.0](https://www.npmjs.com/package/kong-config-manager) has supported --no-ssl. Many thanks to @azachar for his contribution! 👍
